databaseChangeLog:
  - changeSet:
      id: initial_changeset_1
      author: TheYoungBiba
      changes:
        - sqlFile:
            dbms: postgresql
            encoding: utf8
            path: changelog/0_0_1/init_sport_0_0_1.sql
            relativeToChangelogFile: false
            splitStatements: true
            stripComments: true
        - sqlFile:
            dbms: postgresql
            encoding: utf8
            path: changelog/0_0_1/users/init_users_0_0_1.sql
            relativeToChangelogFile: false
            splitStatements: true
            stripComments: true
        - sqlFile:
            dbms: postgresql
            encoding: utf8
            path: changelog/0_0_1/users/init_passport_0_0_1.sql
            relativeToChangelogFile: false
            splitStatements: true
            stripComments: true
        - sqlFile:
            dbms: postgresql
            encoding: utf8
            path: changelog/0_0_1/judge/init_judge_0_0_1.sql
            relativeToChangelogFile: false
            splitStatements: true
            stripComments: true
        - sqlFile:
            dbms: postgresql
            encoding: utf8
            path: changelog/0_0_1/judge/init_judge_status_0_0_1.sql
            relativeToChangelogFile: false
            splitStatements: true
            stripComments: true
        - sqlFile:
            dbms: postgresql
            encoding: utf8
            path: changelog/0_0_1/sportsmen/init_sportsmen_0_0_1.sql
            relativeToChangelogFile: false
            splitStatements: true
            stripComments: true
        - sqlFile:
            dbms: postgresql
            encoding: utf8
            path: changelog/0_0_1/sportsmen/init_sportsmen_sport_0_0_1.sql
            relativeToChangelogFile: false
            splitStatements: true
            stripComments: true
        - sqlFile:
            dbms: postgresql
            encoding: utf8
            path: changelog/0_0_1/sportsmen/init_sanction_0_0_1.sql
            relativeToChangelogFile: false
            splitStatements: true
            stripComments: true
        - sqlFile:
            dbms: postgresql
            encoding: utf8
            path: changelog/0_0_1/sportsmen/init_sportsmen_sanction_0_0_1.sql
            relativeToChangelogFile: false
            splitStatements: true
            stripComments: true
        - sqlFile:
            dbms: postgresql
            encoding: utf8
            path: changelog/0_0_1/sportsmen/init_club_0_0_1.sql
            relativeToChangelogFile: false
            splitStatements: true
            stripComments: true
        - sqlFile:
            dbms: postgresql
            encoding: utf8
            path: changelog/0_0_1/sportsmen/init_category_0_0_1.sql
            relativeToChangelogFile: false
            splitStatements: true
            stripComments: true
        - sqlFile:
            dbms: postgresql
            encoding: utf8
            path: changelog/0_0_1/sportsmen/init_sportsmen_achievements_0_0_1.sql
            relativeToChangelogFile: false
            splitStatements: true
            stripComments: true
        - sqlFile:
            dbms: postgresql
            encoding: utf8
            path: changelog/0_0_1/sportsmen/init_sport_role_0_0_1.sql
            relativeToChangelogFile: false
            splitStatements: true
            stripComments: true
        - sqlFile:
            dbms: postgresql
            encoding: utf8
            path: changelog/0_0_1/tournament/init_tournament_0_0_1.sql
            relativeToChangelogFile: false
            splitStatements: true
            stripComments: true
        - sqlFile:
            dbms: postgresql
            encoding: utf8
            path: changelog/0_0_1/tournament/init_tournament_part_0_0_1.sql
            relativeToChangelogFile: false
            splitStatements: true
            stripComments: true
        - sqlFile:
            dbms: postgresql
            encoding: utf8
            path: changelog/0_0_1/tournament/init_tournament_part_team_0_0_1.sql
            relativeToChangelogFile: false
            splitStatements: true
            stripComments: true
        - sqlFile:
            dbms: postgresql
            encoding: utf8
            path: changelog/0_0_1/tournament/init_tournament_part_tournament_part_team_0_0_1.sql
            relativeToChangelogFile: false
            splitStatements: true
            stripComments: true
        - sqlFile:
            dbms: postgresql
            encoding: utf8
            path: changelog/0_0_1/tournament/init_tournament_part_judge_0_0_1.sql
            relativeToChangelogFile: false
            splitStatements: true
            stripComments: true
        - sqlFile:
            dbms: postgresql
            encoding: utf8
            path: changelog/0_0_1/tournament/init_tournament_part_team_sportsmen_0_0_1.sql
            relativeToChangelogFile: false
            splitStatements: true
            stripComments: true
        - sqlFile:
            dbms: postgresql
            encoding: utf8
            path: changelog/0_0_1/tournament_maker/init_organization_0_0_1.sql
            relativeToChangelogFile: false
            splitStatements: true
            stripComments: true
        - sqlFile:
            dbms: postgresql
            encoding: utf8
            path: changelog/0_0_1/tournament_maker/init_legal_tournament_maker_0_0_1.sql
            relativeToChangelogFile: false
            splitStatements: true
            stripComments: true
        - sqlFile:
            dbms: postgresql
            encoding: utf8
            path: changelog/0_0_1/tournament_maker/init_user_tournament_maker_0_0_1.sql
            relativeToChangelogFile: false
            splitStatements: true
            stripComments: true
        - sqlFile:
            dbms: postgresql
            encoding: utf8
            path: changelog/0_0_1/tournament_maker/init_tournament_maker_tournament_0_0_1.sql
            relativeToChangelogFile: false
            splitStatements: true
            stripComments: true
        - sqlFile:
            dbms: postgresql
            encoding: utf8
            path: changelog/0_0_1/tournament_maker/init_organization_allowed_sport_0_0_1.sql
            relativeToChangelogFile: false
            splitStatements: true
            stripComments: true
        - sqlFile:
            dbms: postgresql
            encoding: utf8
            path: changelog/0_0_1/season/init_season_0_0_1.sql
            relativeToChangelogFile: false
            splitStatements: true
            stripComments: true
        - sqlFile:
            dbms: postgresql
            encoding: utf8
            path: changelog/0_0_1/season/init_season_tournament_0_0_1.sql
            relativeToChangelogFile: false
            splitStatements: true
            stripComments: true
        - sqlFile:
            dbms: postgresql
            encoding: utf8
            path: changelog/0_0_1/season/init_season_tournament_club_0_0_1.sql
            relativeToChangelogFile: false
            splitStatements: true
            stripComments: true
