openapi: 3.0.2
info:
  title: TheSportManager
  description: It's easy to manage your sport tournament or league
  version: '1.0'
  contact:
    name: SportManager
    url: https://sportmanager.com/support
    email: sportmanager@gmail.com
tags:
  - name: tournament
    description: Everything about tournaments
  - name: user
    description: Everything about users
paths:
  /api/v1/tournament:
    $ref: paths/api_v1_tournament.yaml
  /api/v1/tournament/{id}:
    $ref: paths/api_v1_tournament_{id}.yaml
  /api/v1/users:
    $ref: paths/api_v1_users.yaml
  /api/v1/users/{id}:
    $ref: paths/api_v1_users_{id}.yaml
  /api/v1/users/sportsmen:
    $ref: paths/api_v1_users_sportsmen.yaml
  /api/v1/users/{id}/sportsmen:
    $ref: paths/api_v1_users_{id}_sportsmen.yaml
  /api/v1/users/sportsmen_sport:
    $ref: paths/api_v1_users_sportsmen_sport.yaml
  /api/v1/users/{id}/sportsmen_sport:
    $ref: paths/api_v1_users_{id}_sportsmen_sport.yaml
  /api/v1/users/tournament_maker:
    $ref: paths/api_v1_users_tournament_maker.yaml
  /api/v1/users/{id}/tournament_maker:
    $ref: paths/api_v1_users_{id}_tournament_maker.yaml
  /api/v1/users/legal_tournament_maker:
    $ref: paths/api_v1_users_legal_tournament_maker.yaml
  /api/v1/users/{id}/legal_tournament_maker:
    $ref: paths/api_v1_users_{id}_legal_tournament_maker.yaml
  /api/v1/users/judge:
    $ref: paths/api_v1_users_judge.yaml
  /api/v1/users/{id}/judge:
    $ref: paths/api_v1_users_{id}_judge.yaml
  /api/v1/users/organizer:
    $ref: paths/api_v1_users_organizer.yaml
  /api/v1/users/{id}/organizer:
    $ref: paths/api_v1_users_{id}_organizer.yaml
  /api/v1/users/sportsmen_sport/sportsmen_achievements:
    $ref: paths/api_v1_users_sportsmen_sport_sportsmen_achievements.yaml
  /api/v1/users/{id}/sportsmen_sport/sportsmen_achievements:
    $ref: paths/api_v1_users_{id}_sportsmen_sport_sportsmen_achievements.yaml
  /api/v1/users/sportsmen/sportsmen_sanction:
    $ref: paths/api_v1_users_sportsmen_sportsmen_sanction.yaml
  /api/v1/users/{id}/sportsmen/sportsmen_sanction:
    $ref: paths/api_v1_users_{id}_sportsmen_sportsmen_sanction.yaml
  /api/v1/organizations:
    $ref: paths/api_v1_organizations.yaml
  /api/v1/organizations/{id}:
    $ref: paths/api_v1_organizations_{id}.yaml
  /api/v1/organization-allowed-sports:
    $ref: paths/api_v1_organization-allowed-sports.yaml
  /api/v1/organization-allowed-sports/{organization_id}:
    $ref: paths/api_v1_organization-allowed-sports_{organization_id}.yaml
  /api/v1/organization-allowed-sports/{organization_id}/{sport_id}:
    $ref: paths/api_v1_organization-allowed-sports_{organization_id}_{sport_id}.yaml
  /api/v1/tournament/tournament-part-judges:
    $ref: paths/api_v1_tournament_tournament-part-judges.yaml
  /api/v1/tournament/tournament-part-judges/{tournament_part_id}/{judge_id}:
    $ref: >-
      paths/api_v1_tournament_tournament-part-judges_{tournament_part_id}_{judge_id}.yaml
  /api/v1/tournament/tournament-part-judges/{tournament_part_id}:
    $ref: paths/api_v1_tournament_tournament-part-judges_{tournament_part_id}.yaml
