openapi: 3.0.2
info:
  title: "TheSportManager"
  description: "It's easy to manage your sport tournament or league"
  version: "1.0"
  contact:
    name: "SportManager"
    url: "https://sportmanager.com/support"
    email: "sportmanager@gmail.com"
tags:
  - name: tournament
    description: "Everything about tournaments"
  
paths:
  /tournament:
    get:
      tags:
        - tournament
      summary: "Shows all the existed tournaments"
      description: "All the tournaments from every sport direction"
      responses:
        '200':
          description: "operation was successful"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TournamentRequest'
        '400':
          description: "operation was failed"

    post:
      summary: "Make a new tournament"
      requestBody:
        description: "All the details data"
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TournamentRequest'
      responses:
        '201':
          description: "Operation was successful"
        '400':
          description: "Operation was failed"

  /tournament/{id}:
    put:
      tags:
        - tournament
      summary: "Change a tournament details"
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        description: "All the details data"
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TournamentRequest'
      responses:
        '201':
          description: "Operation was successful"
        '400':
          description: "Operation was failed"
          
    delete:
      tags:
        - tournament
      summary: "Delete the existing tournament by Id"
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: "Operation was successful"
        '400':
          description: "Operation was failed"

  /users:
    post:
      summary: "Create new user"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRequest'
      responses:
        '201':
          description: "User was created"
        '400':
          description: "Operation was failed"
          
    get:
      summary: "Show all the existed users"
      description: "To get list of every user from database"
      responses:
        '200':
          description: "operation was successful"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserRequest'
        '400':
          description: "operation was failed"
        
  /users/{id}:
    get:
      summary: "To get user by ID"
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: "Данные пользователя"
          
    put:
      summary: "To update user by ID"
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        description: "The data for user update"
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRequest'
      responses:
        '201':
          description: "Operation was successful"
        '400':
          description: "Operation was failed"
          
    delete:
     summary: "To delete user by id"
     parameters:
       - in: path
         name: id
         required: true
         schema:
           type: integer
         description: "User id"
     responses:
        '204':
         description: "Removable was successful"
        '400':
          description: "Operation was failed" 

  /users/sportsmen:
    get:
      summary: "Show all the existed sportsmen"
      description: "To get list of every sportsman from database"
      responses:
        '200':
          description: "operation was successful"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SportsmenRequest'
        '400':
          description: "operation was failed"

  /users/{id}/sportsmen:
    post:
      summary: "To add sportsman role for user"
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        description: "The sportsmen data"
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SportsmenRequest'
      responses:
        '201':
          description: "Role was added successful"
        '400':
          description: "Operation was failed" 
          
    delete:
      summary: "To delete sportsman role by id"
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: "User id"
      responses:
        '204':
         description: "Removable was successful"
        '400':
          description: "Operation was failed" 
         
  /users/sportsmen_sport:
    post:
      summary: "To add sportsman to new sport"
      requestBody:
        description: "The sportsman data"
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SportsmenSportRequest'
      responses:
        '201':
          description: "Opearation was successful"
        '400':
          description: "Operation was failed" 

  /users/{id}/sportsmen_sport:
    get:
      summary: "To get sportsman data by ID"
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: "Operation was successfful"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SportsmenSportRequest'
        '400':
          description: "Operation was failed" 

    put:
      summary: "To update sportsman data in sport by ID"
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        description: "The updated sportsman data"
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SportsmenSportRequest'
      responses:
        '201':
          description: "Operation was successful"
        '400':
          description: "Operation was failed" 

    delete:
      summary: "To remove sportsman from sport by ID"
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: "Sportsman was removed from sport"
        '400':
          description: "Operation was failed" 

  
  /users/tournament_maker:
    get:
      summary: "Show all the existed tournament makers"
      description: "To get list of every tournament maker from database"
      responses:
        '200':
          description: "operation was successful"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TournamentMakerRequest'
        '400':
          description: "operation was failed"
  
  /users/{id}/tournament_maker:
    post:
      summary: "To add tournament maker role to user by id"
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        description: "The tournament maker data"
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TournamentMakerRequest'
      responses:
        '201':
          description: "Role was added"
        '400':
          description: "Operation was failed" 
          
    delete:
     summary: "To delete tournament maker role by id"
     parameters:
       - in: path
         name: id
         required: true
         schema:
           type: integer
         description: "User id"
     responses:
       '204':
         description: "Removable was successful"

  /users/legal_tournament_maker:
    get:
      summary: "Show all the existed legal tournament makers"
      description: "To get list of every legal tournament maker from database"
      responses:
        '200':
          description: "operation was successful"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LegalTournamentMakerRequest'
        '400':
          description: "operation was failed"  
  
  /users/{id}/legal_tournament_maker:
    post:
      summary: "To add legal tournament maker role to user by ID"
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        description: "The legal tournament maker dataa"
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LegalTournamentMakerRequest'
      responses:
        '201':
          description: "The role was added"
        '400':
          description: "Operation was failed" 
          
    delete:
     summary: "To delete legal tournament maker role by id"
     parameters:
       - in: path
         name: id
         required: true
         schema:
           type: integer
         description: "User id"
     responses:
       '204':
         description: "Removable was successful"

  /users/judge:
    get:
      summary: "Show all the existed judges"
      description: "To get list of every judge from database"
      responses:
        '200':
          description: "operation was successful"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/JudgeRequest'
        '400':
          description: "operation was failed"
          
  /users/{id}/judge:
    post:
      summary: "To add judge role"
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        description: "The judge role"
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/JudgeRequest'
      responses:
        '201':
          description: "The judge role was added"
        '400':
          description: "Operation was failed"
          
    delete:
     summary: "To delete judge role by id"
     parameters:
       - in: path
         name: id
         required: true
         schema:
           type: integer
         description: "User id"
     responses:
       '204':
         description: "Removable was successful"

          
  /users/organizer:
    get:
      summary: "Show all the existed organizers"
      description: "To get list of every organizer from database"
      responses:
        '200':
          description: "operation was successful"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/OrganizerRequest"
        '400':
          description: "operation was failed"
          
  /users/{id}/organizer:
    post:
      summary: "To add organizer role"
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        description: "The organizer data"
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrganizerRequest'
      responses:
        '201':
          description: "The role was added"
        '400':
          description: "Operation was failed"
          
    delete:
     summary: "To delete organizer role by id"
     parameters:
       - in: path
         name: id
         required: true
         schema:
           type: integer
         description: "User id"
     responses:
       '204':
         description: "Removable was successful"
         
  /users/sportsmen_sport/sportsmen_achievements:
    post:
      requestBody:
        description: "The details about achievement"
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SportsmenAchievementRequest'
      responses:
        '201':
          description: "The achievement was added"
        '400':
          description: "Operation was failed"       
         
  /users/{id}/sportsmen_sport/sportsmen_achievements:
    get:
      summary: "To get the sportsman achievements by sportsmen_id"
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: "sportsmen_id"
      responses:
        '200':
          description: "Achievement was found"
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/SportsmenAchievementRequest'
        '400':
          description: "Operation was failed" 

    put:
      summary: "To update the sportsman achievement by sportsmen_achievement id"
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: "Id from sportsmen_achievement table"
      requestBody:
        description: "Updated data about achievement"
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SportsmenAchievementRequest'
      responses:
        '201':
          description: "The achievement was updated"
        '400':
          description: "Operation was failed" 
        
    delete:
      summary: "To delete sportsmen achievement by id from sportsmen_achievement table"
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: "The achievement was removed"
        '400':
          description: "Operation was failed" 

          
components:
  schemas:
    UserRequest:
      type: object
      required:
        - login
        - email
        - phone_number
        - password
      properties:
        login:
          type: string
        email:
          type: string
          format: email
        phone_number:
          type: string
        photo_id:
          type: string
        first_name:
          type: string
        last_name:
          type: string
        patronymic:
          type: string
        password:
          type: string
          
    SportsmenRequest:
      type: object
      required:
        - user_id
        - birthday
        - is_male
      properties:
        user_id:
          type: integer
        birthday:
          type: string
          format: date
        is_male:
          type: boolean
        height:
          type: number
          format: float
        height_updated_at:
          type: string
          format: date-time
        height_checked_at:
          type: string
          format: date-time
        weight:
          type: number
          format: float
        weight_updated_at:
          type: string
          format: date-time
        weight_checked_at:
          type: string
          format: date-time
        club_id:
          type: integer
          
    SportsmenSportRequest:
      type: object
      required:
        - sport_id
        - sportsmen_id
        - rating
      properties:
        sport_id:
          type: integer
        sportsmen_id:
          type: integer
        category_id:
          type: integer
        role_id:
          type: integer
        rank:
          type: string
        license:
          type: string
        rating:
          type: number
          format: float
          
    SportsmenAchievementRequest:
      type: object
      required:
        - sportsmen_sport_id
        - place
        - achieved_at_year
      properties:
        sportsmen_sport_id:
          type: integer
        place:
          type: integer
        tournament_id:
          type: integer
        achieved_with_category_id:
          type: integer
        description:
          type: string
        achieved_at_year:
          type: string
          format: date
          
    TournamentRequest:
      type: object
      required:
        - name
        - place
        - start_time
        - end_time
        - is_official
        - tournament_parts
      properties:
        name:
          type: string
        sport_id:
          type: integer
        place:
          type: string
        start_time:
          type: string
          format: date
        end_time:
          type: string
          format: date
        is_official:
          type: boolean
        participation_fee:
          type: integer
        max_count_commands:
          type: integer
        tournament_parts:
          type: array
          items:
            $ref: '#/components/schemas/TournamentPartRequest'

    TournamentPartRequest:
      type: object
      required:
        - name
        - start_time
        - end_time
        - category_id
      properties:
        name:
          type: string
        start_time:
          type: string
          format: date-time
        end_time:
          type: string
          format: date-time
        category_id:
          type: integer
        tournament_part_teams:
          type: array
          items:
            $ref: '#/components/schemas/TournamentPartTeamRequest'

    TournamentPartTeamRequest:
      type: object
      required:
        - name
      properties:
        name:
          type: string
        result:
          type: integer
  
    TournamentMakerRequest:
      type: object
      required:
        - organization_id
      properties:
        organization_id:
          type: integer
          
    LegalTournamentMakerRequest:
      type: object
      required:
        - organization_id
      properties:
        organization_id:
          type: integer
          description: "ID организации, связанной с пользователем"
          
    JudgeRequest:
      type: object
      required:
        - status_id
      properties:
        status_id:
          type: integer
          description: "ID статуса судьи"
          
    OrganizerRequest:
      type: object
      required:
        - email
        - status
      properties:
        email:
          type: string
          format: email
          description: "Электронная почта организатора"
        status:
          type: string
          description: "Статус организатора"
        inn:
          type: string
          description: "ИНН организатора"









