openapi: 3.0.2
info:
  title: "TheSportManager"
  description: "It's easy to manage your sport tournament or league"
  version: "1.0"
  contact:
    name: "SportManager"
    url: "https://sportmanager.com/support"
    email: "sportmanager@gmail.com"
tags:
  - name: tournament
    description: "Everything about tournaments"
  - name: user
    description: "Everything about users"
  
paths:
  /api/v1/tournament:
    $ref: './v1/MethodsWithoutParameters/tournament/tournament.yaml'

  /api/v1/tournament/{id}:
    $ref: './v1/MethodsWithParameters/tournament/tournament.yaml'

  /api/v1/users:
    $ref: './v1/MethodsWithoutParameters/users/users.yaml'
        
  /api/v1/users/{id}:
    $ref: './v1/MethodsWithParameters/users/users.yaml'

  /api/v1/users/sportsmen:
    $ref: './v1/MethodsWithoutParameters/users/sportsmen.yaml'

  /api/v1/users/{id}/sportsmen:
    $ref: './v1/MethodsWithParameters/users/sportsmen.yaml'
         
  /api/v1/users/sportsmen_sport:
    $ref: './v1/MethodsWithoutParameters/users/sportsmen_sport.yaml'

  /api/v1/users/{id}/sportsmen_sport:
    $ref: './v1/MethodsWithParameters/users/sportsmen_sport.yaml'

  /api/v1/users/tournament_maker:
    $ref: './v1/MethodsWithoutParameters/users/tournament_maker.yaml'
  
  /api/v1/users/{id}/tournament_maker:
    $ref: './v1/MethodsWithParameters/users/tournament_maker.yaml'

  /api/v1/users/legal_tournament_maker:
    $ref: './v1/MethodsWithoutParameters/users/legal_tournament_maker.yaml'
  
  /api/v1/users/{id}/legal_tournament_maker:
    $ref: './v1/MethodsWithParameters/users/legal_tournament_maker.yaml'

  /api/v1/users/judge:
    $ref: './v1/MethodsWithoutParameters/users/judge.yaml'
          
  /api/v1/users/{id}/judge:
    $ref: './v1/MethodsWithParameters/users/judge.yaml'
    
  /api/v1/users/organizer:
    $ref: './v1/MethodsWithoutParameters/users/organizer.yaml'
          
  /api/v1/users/{id}/organizer:
    $ref: './v1/MethodsWithParameters/users/organizer.yaml'

  /api/v1/users/sportsmen_sport/sportsmen_achievements:
    $ref: './v1/MethodsWithoutParameters/users/sportsmen_achievements.yaml'
         
  /api/v1/users/{id}/sportsmen_sport/sportsmen_achievements:
    $ref: './v1/MethodsWithParameters/users/sportsmen_achievements.yaml'