spring:
  application:
    name: tournament-storage
  profiles:
    active: local
  jpa:
    open-in-view: off
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
  main:
    banner-mode: off

server:
  port: 8080